exclude: [
  'bower_components',
  'node_modules',
  'Gruntfile.coffee',
  'bower.json',
  'Gemfile',
  'Gemfile.lock',
  'package.json',
  'Readme.md'
]

timezone: 'America/New_York'

collections:
  tools:
    output: true
  projects:
    output: true
